language: c
compiler:
    - gcc
env:
    - CC=i586-mingw32msvc-gcc CXX=i586-mingw32msvc-g++ LD=i586-mingw32msvc-ld

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq g++-multilib
    - sudo apt-get install -qq mingw32
    - sudo apt-get install -qq pidgin-dev

script: make
