language: c

env:
    - FEATURE=Linux MAKEFILE=Makefile
#    - FEATURE=Windows MAKEFILE=Makefile.mingw CC=i586-mingw32msvc-gcc CXX=i586-mingw32msvc-g++ LD=i586-mingw32msvc-ld

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq g++-multilib
    - sudo apt-get install -qq mingw32
    - sudo apt-get install -qq pidgin-dev

script:
    - echo "Build for $FEATURE"
    - make -f $MAKEFILE

after_script: 

deploy:
    provider: releases
    api_key:
      secure: TmnCFTEVA4wGYUjiAD9ivD8AiyH7UOfwHn33yg/5bvQbTx5OCHWVGSUvnY7zbezIJq56lrGCQ14tJhUVRVtWxyJJXV1WBmmc1kuKeeUTOza68M7G2pHRhoJ0mO9FAaBr/62STuSfovIlSRF3kfJI+/jmxFd0aqaxc4MvV855Aew=
    file:
        - xmpp_muc_presence_plugin.so
    on:
        tags: true
        all_branches: true
